<h1 style="text-align: center;">Pytorch Basics: Tensor</h1>

## 1. Introduction  
This notebook is a part of a part of my journey to learn Pytorch and deep learning. It serves as a reference for me and others who are interested in learning Pytorch. In this notebook, I will cover two important concepts in Pytorch: Tensor that are, to my experience, the core of Pytorch. Along with the concepts, I will also provide some examples to illustrate how to use them.
## 2. Tensor
### 2.1 What is Tensor?
This is from [Pytorch documentation](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html): *"Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters. Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing. If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along in this quick API walkthrough."*
[NumPy Illustrated: The visual guide to Numpy](https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d)
### 2.2 Tensor Creation


In [1]:
import numpy as np
import torch

# create from data
data = [[1, 2], [3, 4]]
tensor_data = torch.tensor(data)
print(f'This tensor is created from data:\n {tensor_data}')

# create from numpy
np_array = np.array([[1, 2], [3, 4]])
tensor_np = torch.from_numpy(np_array)
print(f'This tensor is created from numpy:\n {tensor_np}')

# create from another tensor
tensor_ones = torch.ones_like(tensor_data) # create a tensor of 1s with the same shape as tensor_data
print(f'This tensor is created from another tensor:\n {tensor_ones}')


This tensor is created from data:
 tensor([[1, 2],
        [3, 4]])
This tensor is created from numpy:
 tensor([[1, 2],
        [3, 4]])
This tensor is created from another tensor:
 tensor([[1, 1],
        [1, 1]])


In [2]:
# create a tensor of 1s
tensor_ones = torch.ones(3, 2) # create a tensor of 1s with shape 3x2
print(f'This tensor is created from ones:\n {tensor_ones}')

# create a tensor of 0s
tensor_zeros = torch.zeros(3, 2) # create a tensor of 0s with shape 3x2
print(f'This tensor is created from zeros:\n {tensor_zeros}')

# create a tensor of random values
tensor_rand = torch.rand(3, 2) # create a tensor of random values with shape 3x2
print(f'This tensor is created from random values:\n {tensor_rand}')

# create a tensor with range
tensor_range = torch.arange(0, 15, 2) # create a tensor with values from 0 to 15 with step 2
print(f'This tensor is created from range:\n {tensor_range}')

# create a tensor with linear spcace
sensor_linspace = torch.linspace(0, 10, 5) # create a tensor with 5 values from 0 to 10
print(f'This tensor is created from linear space:\n {sensor_linspace}')

# create a with data type
tensor_data_type = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(f'This tensor is created from data with data type:\n {tensor_data_type}')

This tensor is created from ones:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
This tensor is created from zeros:
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
This tensor is created from random values:
 tensor([[0.0646, 0.5620],
        [0.9739, 0.6127],
        [0.9949, 0.4079]])
This tensor is created from range:
 tensor([ 0,  2,  4,  6,  8, 10, 12, 14])
This tensor is created from linear space:
 tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
This tensor is created from data with data type:
 tensor([[1., 2.],
        [3., 4.]])


In [3]:
# special tensors
tensor_eye = torch.eye(3, 3) # create a tensor of 1s on the diagonal and 0s elsewhere with shape 3x2
print(f'This tensor is created from eye:\n {tensor_eye}')
tensor_zeros = torch.zeros_like(tensor_eye) # create a tensor of 0s with the same shape as tensor_eye
print(f'This tensor is created from zeros_like:\n {tensor_zeros}')
tensor_ones = torch.ones_like(tensor_eye) # create a tensor of 1s with the same shape as tensor_eye
print(f'This tensor is created from ones_like:\n {tensor_ones}')
tensor_empty = torch.empty(3, 2) # create a tensor of uninitialized data with shape 3x2
print(f'This tensor is created from empty:\n {tensor_empty}')

This tensor is created from eye:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
This tensor is created from zeros_like:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
This tensor is created from ones_like:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
This tensor is created from empty:
 tensor([[0.3773, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000]])


### 2.3 Tensor Attributes
As tensor is data structure, it have some attributes associated with it. Some of the important attributes are: shape, data type(dtypes), device (where data is stored), requires_grad (whether to calculate gradients or not), and names:
- shape: shape of the tensor tells us about the number of elements in each dimension.
- dtype: data type of the tensor.
- device: device where the tensor is stored.
- requires_grad: whether to calculate gradients or not. This attribute will signal Pytorch that computational graph should be constructed. It is useful when autograd is required. More on autograd can be found [here](notebooks/autograd.ipynb).
- names: names of the tensor. it is bookkeeping feasture that help to keep track of tensor dimensions' names.

All these attribute can assigned to tensor during creation or can be changed later using tensor's methods. Let's have a look:

In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor_rand = torch.rand(3, 2, dtype=torch.float32, device=device, requires_grad=True, names=['samples', 'features']) # create a tensor of random numbers with shape 3x2

/tmp/ipykernel_23408/280765653.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /pytorch/c10/core/TensorImpl.h:1935.)
  tensor_rand = torch.rand(3, 2, dtype=torch.float32, device=device, requires_grad=True, names=['samples', 'features']) # create a tensor of random numbers with shape 3x2


In [5]:
# shape of tensor
print(f'This is tensor_rand:\n {tensor_rand}')
print(f'This is shape of tensor_rand: {tensor_rand.shape}')
print(f'This is name of each dimension of tensor_rand: {tensor_rand.names}')
print(f'This tensor_rand is on device: {tensor_rand.device}')
print(f'This tensor_rand is requires_grad: {tensor_rand.requires_grad}')
print(f'The gradient of tensor_rand is: {tensor_rand.grad} (None because we have not computed the gradient yet)')

This is tensor_rand:
 tensor([[0.9423, 0.4784],
        [0.2133, 0.9464],
        [0.3813, 0.6426]], device='cuda:0', requires_grad=True,
       names=('samples', 'features'))
This is shape of tensor_rand: torch.Size([3, 2])
This is name of each dimension of tensor_rand: ('samples', 'features')
This tensor_rand is on device: cuda:0
This tensor_rand is requires_grad: True
The gradient of tensor_rand is: None (None because we have not computed the gradient yet)


### 2.4 Tensor Reshape and Index
The syxtax for reshaping and indexing tensor is similar to NumPy. Note that when do reshape, the number of elements in the reshaped tensor should be equal to the number of elements in the original tensor. Let's have a look at some examples:

In [6]:
tensor_1D = torch.arange(1, 21, 1) # create a 1D tensor with values from 1 to 20
print(f'this is tensor_reshape:\n {tensor_1D}')
print(f'convert 1D tensor to 2D tensor: \n {tensor_1D.reshape(4, 5)}') # first dim has 4 elements, second dim has 5 elements
print(f'convert 1D tensor to 3D tensor: \n {tensor_1D.reshape(2, 2, 5)}') # first dim has 2 elements, second dim has 2 elements, third dim has 5 elements
print(f'convert 1D tensor to 4D tensor: \n {tensor_1D.reshape(2, 2, 1, 5)}') # first dim has 2 elements, second dim has 2 elements, third dim has 1 element, fourth dim has 5 elements
print(f'convert 1D tensor to 5D tensor: \n {tensor_1D.reshape(2, 2, 1, 1, 5)}') # first dim has 2 elements, second dim has 2 elements, third dim has 1 element, fourth dim has 1 element, fifth dim has 5 elements
print(f'convert 1D tensor to 2D tensor with -1: \n {tensor_1D.reshape(4, -1)}') # first dim has 4 elements, the second dim is inferred

this is tensor_reshape:
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
convert 1D tensor to 2D tensor: 
 tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
convert 1D tensor to 3D tensor: 
 tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])
convert 1D tensor to 4D tensor: 
 tensor([[[[ 1,  2,  3,  4,  5]],

         [[ 6,  7,  8,  9, 10]]],


        [[[11, 12, 13, 14, 15]],

         [[16, 17, 18, 19, 20]]]])
convert 1D tensor to 5D tensor: 
 tensor([[[[[ 1,  2,  3,  4,  5]]],


         [[[ 6,  7,  8,  9, 10]]]],



        [[[[11, 12, 13, 14, 15]]],


         [[[16, 17, 18, 19, 20]]]]])
convert 1D tensor to 2D tensor with -1: 
 tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


In [7]:
# reshape tensor use unsqueeze and squeeze
tensor_squeeze = torch.arange(1, 16, 1).reshape(5, 3)
print(f'this is tensor_squeeze:\n {tensor_squeeze}')
print(f'this is tensor_squeeze after unsqueeze with shape {tensor_squeeze.unsqueeze(0).shape}:\n {tensor_squeeze.unsqueeze(0)}') # add a dimension at index 0
print(f'this is tensor_squeeze after unsqueeze with {tensor_squeeze.unsqueeze(1).shape}:\n {tensor_squeeze.unsqueeze(1)}') # add a dimension at index 1

this is tensor_squeeze:
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
this is tensor_squeeze after unsqueeze with shape torch.Size([1, 5, 3]):
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]]])
this is tensor_squeeze after unsqueeze with torch.Size([5, 1, 3]):
 tensor([[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]],

        [[13, 14, 15]]])


In [8]:
# we can also use squeeze to remove the dimension
tensor_unsqueeze = torch.arange(1, 16, 1).reshape(1, 5, 3)
print(f'this is tensor_unsqueeze with {tensor_unsqueeze.shape}:\n {tensor_unsqueeze}')
print(f'this is tensor_unsqueeze after squeeze with shape {tensor_unsqueeze.squeeze(0).shape}:\n {tensor_unsqueeze.squeeze(0)}') # remove the dimension at index 0

this is tensor_unsqueeze with torch.Size([1, 5, 3]):
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]]])
this is tensor_unsqueeze after squeeze with shape torch.Size([5, 3]):
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [9]:
# create a tensor for indexing
tensor_index = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'This is tensor_index:\n {tensor_index}')

This is tensor_index:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [10]:
print(f'Get all rows and the first columns: \n {tensor_index[:, 0]}')
print(f'Get the last row and last column: \n {tensor_index[-1, -1]}')
print(f'Get first row and all columns: \n {tensor_index[0, :]}')
print(f'Get elements that larger than 3: \n {tensor_index[tensor_index > 3]}')
print(f'Get elements that larger than 3 and less than 8: \n {tensor_index[(tensor_index > 3) & (tensor_index < 8)]}')

Get all rows and the first columns: 
 tensor([1, 4, 7])
Get the last row and last column: 
 9
Get first row and all columns: 
 tensor([1, 2, 3])
Get elements that larger than 3: 
 tensor([4, 5, 6, 7, 8, 9])
Get elements that larger than 3 and less than 8: 
 tensor([4, 5, 6, 7])


### 2.5 Tensor Operations

In [11]:
# operations with a scalar
ones = torch.ones(3, 2)
print(f'This is ones:\n {ones}')
twos = ones + 1
print(f'This is ones + 1:\n {twos}')
threes = ones * 3
print(f'This is ones * 3:\n {threes}')
ones_again = threes / 3
print(f'This is threes / 3:\n {ones_again}')

This is ones:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
This is ones + 1:
 tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
This is ones * 3:
 tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])
This is threes / 3:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [12]:
# operation with another tensor
tensor_1 = torch.tensor([[1, 2], [3, 4]])
tensor_2 = torch.tensor([[5, 6], [7, 8]])
print(f'This is tensor_1:\n {tensor_1}')
print(f'This is tensor_2:\n {tensor_2}')

This is tensor_1:
 tensor([[1, 2],
        [3, 4]])
This is tensor_2:
 tensor([[5, 6],
        [7, 8]])


In [13]:
# element-wise operations
tensor_1_plus_2 = tensor_1 + tensor_2
print(f'This is tensor_1 + tensor_2:\n {tensor_1_plus_2}')
tensor_1_mul_2 = tensor_1 * tensor_2
print(f'This is tensor_1 * tensor_2:\n {tensor_1_mul_2}')
tensor_1_div_2 = tensor_1 / tensor_2
print(f'This is tensor_1 / tensor_2:\n {tensor_1_div_2}')

This is tensor_1 + tensor_2:
 tensor([[ 6,  8],
        [10, 12]])
This is tensor_1 * tensor_2:
 tensor([[ 5, 12],
        [21, 32]])
This is tensor_1 / tensor_2:
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


It can be seen that tensor operation with a scalar and another tensor with same shape is element-wise operation. Let's have a look at some cases when we do operations with two tensors with different shapes:

In [14]:
# operation with different shapes
shape_1D = torch.tensor([8, 9, 10])
shape_2D = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'This is shape of shape_1D:\n {shape_1D.shape}')
print(f'This is shape of shape_2D:\n {shape_2D.shape}')

This is shape of shape_1D:
 torch.Size([3])
This is shape of shape_2D:
 torch.Size([3, 3])


In this case, the tensor shape_1D is one dimension or vector. The shape_2D is two dimension or matrix of 2 rows and 3 columns. Similar with numpy, pytorch will operate broadcast operation. The smaller tensor will be broadcasted to match the shape of the larger tensor.

Note often dimension are ordered from left to right equivalent to global to local. The broadcast rules are:
- Matching from right to left.
- If the dimension is 1, it will be broadcasted to match the larger tensor.
- If the dimension are different and None is 1, it raise an error.
Let's have a look at some examples:

In [15]:
# This first will add 1 dimension to shape_1D (3,) -> (1, 3) then broadcast to shape (2, 3) to match shape_2D
# Now two tensors are same shape and can be added
# This is first dimension/row matching
shape_1D + shape_2D

tensor([[ 9, 11, 13],
        [12, 14, 16],
        [15, 17, 19]])

In [16]:
# this produce same result as above
shape_1D_row_unqueeze = shape_1D.unsqueeze(0) # add a dimension at index 0
shape_2D + shape_1D_row_unqueeze

tensor([[ 9, 11, 13],
        [12, 14, 16],
        [15, 17, 19]])

In [17]:
# This will broadcast by second dimension/column matching
shape_1D_col_unsqueeze = shape_1D.unsqueeze(1) # add a dimension at index 1
print(f'this is shape_1D_col_unsqueeze:\n {shape_1D_col_unsqueeze}')
print(f'this is shape_2D:\n {shape_2D}')
print(f'this is shape_1D_col_unsqueeze + shape_2D:\n {shape_1D_col_unsqueeze + shape_2D}')

this is shape_1D_col_unsqueeze:
 tensor([[ 8],
        [ 9],
        [10]])
this is shape_2D:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
this is shape_1D_col_unsqueeze + shape_2D:
 tensor([[ 9, 10, 11],
        [13, 14, 15],
        [17, 18, 19]])


## 3. Conclusion
In this notebook, I have covered the basics of Pytorch tensor. I have explained what is tensor and how to create a tensor in Pytorch.